CREATE TABLE MouseMats (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Brand VARCHAR(30) NOT NULL,
	Material VARCHAR(20) NOT NULL,
	Length FLOAT NULL,
	Width FLOAT NULL,
	Color VARCHAR(10) NOT NULL,
	Price FLOAT NOT NULL
);